version: "3"
services:
  dnws:
    # replace username/repo:tag with your name and image details
    image: tmwatchanan/dnws:hw3
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.25"
          memory: 500M
      restart_policy:
        condition: on-failure
    ports:
      - "80:8080"
    networks:
      - webnet
  redis:
    image: redis
    networks:
      - webnet
networks:
  webnet:
